version: '3'
services:
  #  컨테이너
  nest:
    #    컨테이너의 호칭
    container_name: test
    #    빌드에 사용하는 이미지 혹은 도커파일(저희의 경우 도커파일.)
    build:
      context: .
      dockerfile: Dockerfile
    #      외부 포트 : 내부 포트
    ports:
      - '3000:3000'
    env_file:
      - .env
    #    이 컨테이너에서 사용할 다른 컨테이너(docker compose 의 특장점?)
    depends_on:
      - mysql
  # 운영서버에서 얘 쓰면 좆됨
  mysql:
    image: mysql:latest
    #    비밀번호 값을 해시해서 보관하는 옵션을 준대요
    #command: --default-authentication-plugin=mysql_native_password
    #    환경변수 설정
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: ${{ secret.DB_SCHEMA }}
      TZ: Asia/Seoul
    ports:
      - '3307:3306'