name: github actions env actions
on:
  push:
    branches:
      - main
env:
  DB_HOST: ${{ secrets.DB_HOST }}
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Test
        run: echo $DB_HOST, ${{ secrets.DB_HOST }}